// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zxq97/relation/app/relationship/pkg/dal/model"
)

func newUserRelationCount(db *gorm.DB, opts ...gen.DOOption) userRelationCount {
	_userRelationCount := userRelationCount{}

	_userRelationCount.userRelationCountDo.UseDB(db, opts...)
	_userRelationCount.userRelationCountDo.UseModel(&model.UserRelationCount{})

	tableName := _userRelationCount.userRelationCountDo.TableName()
	_userRelationCount.ALL = field.NewAsterisk(tableName)
	_userRelationCount.UID = field.NewInt64(tableName, "uid")
	_userRelationCount.FollowCount = field.NewInt32(tableName, "follow_count")
	_userRelationCount.FollowerCount = field.NewInt32(tableName, "follower_count")
	_userRelationCount.CreateAt = field.NewTime(tableName, "create_at")
	_userRelationCount.UpdateAt = field.NewTime(tableName, "update_at")

	_userRelationCount.fillFieldMap()

	return _userRelationCount
}

type userRelationCount struct {
	userRelationCountDo userRelationCountDo

	ALL           field.Asterisk
	UID           field.Int64
	FollowCount   field.Int32
	FollowerCount field.Int32
	CreateAt      field.Time
	UpdateAt      field.Time

	fieldMap map[string]field.Expr
}

func (u userRelationCount) Table(newTableName string) *userRelationCount {
	u.userRelationCountDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userRelationCount) As(alias string) *userRelationCount {
	u.userRelationCountDo.DO = *(u.userRelationCountDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userRelationCount) updateTableName(table string) *userRelationCount {
	u.ALL = field.NewAsterisk(table)
	u.UID = field.NewInt64(table, "uid")
	u.FollowCount = field.NewInt32(table, "follow_count")
	u.FollowerCount = field.NewInt32(table, "follower_count")
	u.CreateAt = field.NewTime(table, "create_at")
	u.UpdateAt = field.NewTime(table, "update_at")

	u.fillFieldMap()

	return u
}

func (u *userRelationCount) WithContext(ctx context.Context) *userRelationCountDo {
	return u.userRelationCountDo.WithContext(ctx)
}

func (u userRelationCount) TableName() string { return u.userRelationCountDo.TableName() }

func (u userRelationCount) Alias() string { return u.userRelationCountDo.Alias() }

func (u *userRelationCount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userRelationCount) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["uid"] = u.UID
	u.fieldMap["follow_count"] = u.FollowCount
	u.fieldMap["follower_count"] = u.FollowerCount
	u.fieldMap["create_at"] = u.CreateAt
	u.fieldMap["update_at"] = u.UpdateAt
}

func (u userRelationCount) clone(db *gorm.DB) userRelationCount {
	u.userRelationCountDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userRelationCount) replaceDB(db *gorm.DB) userRelationCount {
	u.userRelationCountDo.ReplaceDB(db)
	return u
}

type userRelationCountDo struct{ gen.DO }

// sql(insert into user_relation_counts (uid, follow_count) values (@uid, 1) on duplicate key update follow_count=follow_count+1)
func (u userRelationCountDo) IncrFollowCount(uid int64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uid)
	generateSQL.WriteString("insert into user_relation_counts (uid, follow_count) values (?, 1) on duplicate key update follow_count=follow_count+1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// sql(update user_relation_counts set follow_count=follow_count-1 where uid=@uid limit 1)
func (u userRelationCountDo) DecrFollowCount(uid int64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uid)
	generateSQL.WriteString("update user_relation_counts set follow_count=follow_count-1 where uid=? limit 1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// sql(insert into user_relation_counts (uid, follower_count) values (@uid, @cnt) on duplicate key update follower_count=follower_count+@cnt)
func (u userRelationCountDo) IncrByFollowerCount(uid int64, cnt int64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uid)
	params = append(params, cnt)
	params = append(params, cnt)
	generateSQL.WriteString("insert into user_relation_counts (uid, follower_count) values (?, ?) on duplicate key update follower_count=follower_count+? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// sql(update user_relation_counts set follower_count=follower_count-@cnt where uid=@uid limit 1)
func (u userRelationCountDo) DecrByFollowerCount(uid int64, cnt int64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, cnt)
	params = append(params, uid)
	generateSQL.WriteString("update user_relation_counts set follower_count=follower_count-? where uid=? limit 1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// sql(select uid, follow_count, follower_count user_relation_counts where uid in (@uids))
func (u userRelationCountDo) FindUsersRelationCount(uids []int64) (result []*model.UserRelationCount, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, uids)
	generateSQL.WriteString("select uid, follow_count, follower_count user_relation_counts where uid in (?) ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (u userRelationCountDo) Debug() *userRelationCountDo {
	return u.withDO(u.DO.Debug())
}

func (u userRelationCountDo) WithContext(ctx context.Context) *userRelationCountDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userRelationCountDo) ReadDB() *userRelationCountDo {
	return u.Clauses(dbresolver.Read)
}

func (u userRelationCountDo) WriteDB() *userRelationCountDo {
	return u.Clauses(dbresolver.Write)
}

func (u userRelationCountDo) Session(config *gorm.Session) *userRelationCountDo {
	return u.withDO(u.DO.Session(config))
}

func (u userRelationCountDo) Clauses(conds ...clause.Expression) *userRelationCountDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userRelationCountDo) Returning(value interface{}, columns ...string) *userRelationCountDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userRelationCountDo) Not(conds ...gen.Condition) *userRelationCountDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userRelationCountDo) Or(conds ...gen.Condition) *userRelationCountDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userRelationCountDo) Select(conds ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userRelationCountDo) Where(conds ...gen.Condition) *userRelationCountDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userRelationCountDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userRelationCountDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userRelationCountDo) Order(conds ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userRelationCountDo) Distinct(cols ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userRelationCountDo) Omit(cols ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userRelationCountDo) Join(table schema.Tabler, on ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userRelationCountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userRelationCountDo) RightJoin(table schema.Tabler, on ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userRelationCountDo) Group(cols ...field.Expr) *userRelationCountDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userRelationCountDo) Having(conds ...gen.Condition) *userRelationCountDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userRelationCountDo) Limit(limit int) *userRelationCountDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userRelationCountDo) Offset(offset int) *userRelationCountDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userRelationCountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userRelationCountDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userRelationCountDo) Unscoped() *userRelationCountDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userRelationCountDo) Create(values ...*model.UserRelationCount) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userRelationCountDo) CreateInBatches(values []*model.UserRelationCount, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userRelationCountDo) Save(values ...*model.UserRelationCount) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userRelationCountDo) First() (*model.UserRelationCount, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRelationCount), nil
	}
}

func (u userRelationCountDo) Take() (*model.UserRelationCount, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRelationCount), nil
	}
}

func (u userRelationCountDo) Last() (*model.UserRelationCount, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRelationCount), nil
	}
}

func (u userRelationCountDo) Find() ([]*model.UserRelationCount, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserRelationCount), err
}

func (u userRelationCountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserRelationCount, err error) {
	buf := make([]*model.UserRelationCount, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userRelationCountDo) FindInBatches(result *[]*model.UserRelationCount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userRelationCountDo) Attrs(attrs ...field.AssignExpr) *userRelationCountDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userRelationCountDo) Assign(attrs ...field.AssignExpr) *userRelationCountDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userRelationCountDo) Joins(fields ...field.RelationField) *userRelationCountDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userRelationCountDo) Preload(fields ...field.RelationField) *userRelationCountDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userRelationCountDo) FirstOrInit() (*model.UserRelationCount, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRelationCount), nil
	}
}

func (u userRelationCountDo) FirstOrCreate() (*model.UserRelationCount, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRelationCount), nil
	}
}

func (u userRelationCountDo) FindByPage(offset int, limit int) (result []*model.UserRelationCount, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userRelationCountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userRelationCountDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userRelationCountDo) Delete(models ...*model.UserRelationCount) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userRelationCountDo) withDO(do gen.Dao) *userRelationCountDo {
	u.DO = *do.(*gen.DO)
	return u
}
